function calibrate_navigation(p: player, step: number):

    set {nav.stage.%uuid of {_p}%} to 1
    nextNavigationRound({_p})

function nextNavigationRound(p: player):

    set {nav.target.%uuid of {_p}%} to random integer between 0 and 8
    set {nav.direction.%uuid of {_p}%} to random integer between 0 and 8

    openNavigationGUI({_p})

function openNavigationGUI(p: player):

    set {_inv} to chest inventory with 3 rows named "&9Calibrar Navegação"

    set {_target} to {nav.target.%uuid of {_p}%}
    set {_dir} to {nav.direction.%uuid of {_p}%}

    set slot (9 + {_target}) of {_inv} to lime stained glass pane named "&aAlvo"

    set slot {_dir} of {_inv} to pointed dripstone named "&eDireção"

    set slot 21 of {_inv} to arrow named "&aEsquerda"
    set slot 22 of {_inv} to lime concrete named "&aConfirmar"
    set slot 23 of {_inv} to arrow named "&aDireita"

    open {_inv} to {_p}

on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&9Calibrar Navegação":
        stop

    cancel event

    if clicked slot = 21:

        remove 1 from {nav.direction.%uuid of player%}

        if {nav.direction.%uuid of player%} < 0:
            set {nav.direction.%uuid of player%} to 8

        openNavigationGUI(player)
        stop

    if clicked slot = 23:

        add 1 to {nav.direction.%uuid of player%}

        if {nav.direction.%uuid of player%} > 8:
            set {nav.direction.%uuid of player%} to 0

        openNavigationGUI(player)
        stop

    if clicked slot != 22:
        stop

    if {nav.direction.%uuid of player%} != {nav.target.%uuid of player%}:

        close player's inventory

        delete {nav.target.%uuid of player%}
        delete {nav.direction.%uuid of player%}
        delete {nav.stage.%uuid of player%}

        send "&cVocê conseguiu descalibrar a navegação."

        stop

    add 1 to {nav.stage.%uuid of player%}

    if {nav.stage.%uuid of player%} > 3:

        close player's inventory

        delete {nav.target.%uuid of player%}
        delete {nav.direction.%uuid of player%}
        delete {nav.stage.%uuid of player%}

        advanceTaskStep(player, "calibrate_navigation")
        stop

    nextNavigationRound(player)