function destroy_asteroids(p: player, step: number):


    if {_p} is from floodgate:
        send "&7Essa task foi substituída por um &eDownload &7pois você está na &eBedrock Edition&7." to {_p}
        wait 1 second
        download({_p}, {_step}, "destroy_asteroids")
        stop

    set {_inv} to chest inventory with 6 rows named "&8Destruir Asteroides"

    open {_inv} to {_p}

    set {asteroid.running.%uuid of {_p}%} to true
    set {asteroid.kills.%uuid of {_p}%} to 0
    set {asteroid.step.%uuid of {_p}%} to {_step}

    add 1 to {asteroid.session.%uuid of {_p}%}

    spawnAsteroid({_p})


function spawnAsteroid(p: player):
    
    delete {asteroid.slot.%uuid of {_p}%}
    wait 10 ticks
    if {asteroid.running.%uuid of {_p}%} is not true:
        stop

    add 1 to {asteroid.session.%uuid of {_p}%}

    set {_session} to {asteroid.session.%uuid of {_p}%}

    set {_inv} to {_p}'s current inventory


    if {asteroid.slot.%uuid of {_p}%} is set:
        set slot {asteroid.slot.%uuid of {_p}%} of {_inv} to air

    set {_side} to random integer between 1 and 4


    if {_side} is 1:

        set {_slot::*} to 1,2,3,4,5,6,7

        set {_slot} to random element out of {_slot::*}

        set {_dir::*} to 8,9,10

    else if {_side} is 2:

        set {_slot::*} to 46,47,48,49,50,51,52

        set {_slot} to random element out of {_slot::*}

        set {_dir::*} to -8,-9,-10

    else if {_side} is 3:

        set {_slot::*} to 9,18,27,36

        set {_slot} to random element out of {_slot::*}

        set {_dir::*} to 1,10,-8


    else:

        set {_slot::*} to 17,26,35,44

        set {_slot} to random element out of {_slot::*}

        set {_dir::*} to -1,-10,8

    set {asteroid.slot.%uuid of {_p}%} to {_slot}
    set {asteroid.direction.%uuid of {_p}%} to random element out of {_dir::*}
    set {asteroid.speed.%uuid of {_p}%} to "%random integer between 3 and 10% ticks" parsed as timespan

    set slot {_slot} of {_inv} to fire charge named "&6Asteroide"

    moveAsteroid({_p}, {_session})


function moveAsteroid(p: player, session: number):

    if {asteroid.running.%uuid of {_p}%} is not true:
        stop

    wait {asteroid.speed.%uuid of {_p}%}

    if {_session} is not {asteroid.session.%uuid of {_p}%}:
        stop

    if name of {_p}'s current inventory is not "&8Destruir Asteroides":
        stop

    set {_inv} to {_p}'s current inventory

    set {_old} to {asteroid.slot.%uuid of {_p}%}
    set {_new} to {_old}+{asteroid.direction.%uuid of {_p}%}

    set slot {_old} of {_inv} to air

    if {_new} < 0:
        spawnAsteroid({_p})
        stop

    if {_new} > 53:
        spawnAsteroid({_p})
        stop

    if {_new} is 0 or 9 or 18 or 27 or 36 or 45:
        if {asteroid.direction.%uuid of {_p}%} is -8 or 1 or 10:
            spawnAsteroid({_p})
            stop

    if {_new} is 8 or 17 or 26 or 35 or 44 or 53:
        if {asteroid.direction.%uuid of {_p}%} is 8 or -1 or -10:
            spawnAsteroid({_p})
            stop

    set {asteroid.slot.%uuid of {_p}%} to {_new}

    set slot {_new} of {_inv} to fire charge named "&6Asteroide"

    play sound "minecraft:entity.firework_rocket.blast_far" with volume 0.15 and pitch 2 to {_p}

    moveAsteroid({_p}, {_session})

on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Destruir Asteroides":
        stop

    cancel event

    if index of clicked slot is {asteroid.slot.%uuid of player%}:

        delete {asteroid.slot.%uuid of player%}
        add 1 to {asteroid.session.%uuid of player%}

        play sound "minecraft:entity.generic.explode" with volume 0.5 and pitch 1.8 to player

        set slot index of clicked slot of event-inventory to air

        add 1 to {asteroid.kills.%uuid of player%}

        send "Destruidos: %{asteroid.kills.%uuid of player%}%/10"

        if {asteroid.kills.%uuid of player%} >= 10:

            delete {asteroid.running.%uuid of player%}
            delete {asteroid.direction.%uuid of player%}
            delete {asteroid.speed.%uuid of player%}
            delete {asteroid.session.%uuid of player%}

            close player's inventory

            advanceTaskStep(player, "destroy_asteroids", {asteroid.step.%uuid of player%})

            delete {asteroid.step.%uuid of player%}

            stop

        spawnAsteroid(player)

on inventory close:

    if name of event-inventory is not "&8Destruir Asteroides":
        stop

    add 1 to {asteroid.session.%uuid of player%}

    delete {asteroid.running.%uuid of player%}
    delete {asteroid.slot.%uuid of player%}
    delete {asteroid.direction.%uuid of player%}
    delete {asteroid.speed.%uuid of player%}
    delete {asteroid.kills.%uuid of player%}
    delete {asteroid.step.%uuid of player%}