function organize_armor(p: player, step: number):

    set {_inv} to chest inventory with 4 rows named "&6Organizar Armaduras"


    loop 4 times:
        set {_base} to (loop-number - 1) * 9

        set slot ({_base} + 1) of {_inv} to iron chain named " "
        set slot ({_base} + 3) of {_inv} to iron chain named " "
        set slot ({_base} + 5) of {_inv} to iron chain named " "
        set slot ({_base} + 7) of {_inv} to iron chain named " "

    set {_slots::*} to 0,2,4,6,8,9,11,13,15,17,18,20,22,24,26,27,29,31,33,35


    set {_items::*} to netherite helmet, netherite chestplate, netherite leggings, netherite boots
    add diamond helmet to {_items::*}
    add diamond chestplate to {_items::*}
    add diamond leggings to {_items::*}
    add diamond boots to {_items::*}

    add golden helmet to {_items::*}
    add golden chestplate to {_items::*}
    add golden leggings to {_items::*}
    add golden boots to {_items::*}

    add iron helmet to {_items::*}
    add iron chestplate to {_items::*}
    add iron leggings to {_items::*}
    add iron boots to {_items::*}

    add copper helmet to {_items::*}
    add copper chestplate to {_items::*}
    add copper leggings to {_items::*}
    add copper boots to {_items::*}

    loop 20 times:

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set {_item} to random element out of {_items::*}
        remove {_item} from {_items::*}

        set slot {_slot} of {_inv} to {_item} named " "

    open {_inv} to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&6Organizar Armaduras":
        stop

    if clicked slot is 1 or 3 or 5 or 7 or 10 or 12 or 14 or 16 or 19 or 21 or 23 or 25 or 28 or 30 or 32 or 34:
        cancel event
        stop

    if click type is left mouse button with shift or right mouse button with shift:
        cancel event
        stop

    wait 1 tick

    if player is from floodgate:
        set {_item} to player's cursor slot
        if {_item} is not air:
            loop 36 times:
                if slot (loop-number - 1) of event-inventory is air:
                    set slot (loop-number - 1) of event-inventory to {_item}
                    set player's cursor slot to air

                    stop loop

    loop 5 times:

        set {_x} to (loop-number - 1) * 2

        set {_helmet} to slot {_x} of event-inventory
        set {_chest} to slot ({_x} + 9) of event-inventory
        set {_legs} to slot ({_x} + 18) of event-inventory
        set {_boots} to slot ({_x} + 27) of event-inventory

        if {_helmet} or {_chest} or {_legs} or {_boots} is air:
            stop


        set {_h} to "%type of {_helmet}%"
        set {_c} to "%type of {_chest}%"
        set {_l} to "%type of {_legs}%"
        set {_b} to "%type of {_boots}%"

        replace all " helmet" with "" in {_h}
        replace all " chestplate" with "" in {_c}
        replace all " leggings" with "" in {_l}
        replace all " boots" with "" in {_b}

        if {_h} is not {_c}:
            stop

        if {_h} is not {_l}:
            stop

        if {_h} is not {_b}:
            stop

    close player's inventory
    advanceTaskStep(player, "organize_armor")

on inventory close:

    if name of event-inventory is "&6Organizar Armaduras":

        if player's cursor slot is not air:
            set player's cursor slot to air