function remove_duplicate_books(p: player, step: number):

    set {_inv} to chest inventory with 3 rows named "&8Remover Duplicatas"

    delete {library.duplicateTitles.%uuid of {_p}%::*}
    delete {library.copy.%uuid of {_p}%::*}
    set {library.duplicates.%uuid of {_p}%} to 0

    loop 9 times:
        set slot (loop-number + 17) of {_inv} to gray stained glass pane named " "

    set {_slots::*} to 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17

    set slot 22 of {_inv} to composter named "&2Lixeira"

    set {_titles::*} to "Manual de Segurança"
    add "Como NÃO Explodir o Reator" to {_titles::*}
    add "Como Explodir o Reator" to {_titles::*}
    add "A Arte de Culpar a Engenharia" to {_titles::*}
    add "Café: Mito ou Realidade" to {_titles::*}
    add "Introdução ao Caos Organizado" to {_titles::*}
    add "Como Apertar Botões Profissionalmente" to {_titles::*}
    add "Café Gostoso: Mito ou Realidade?" to {_titles::*}
    add "Guia Definitivo da Gambiarra" to {_titles::*}
    add "Quem Mexeu no Reator?" to {_titles::*}
    add "Relatório Experimental Muito Importante" to {_titles::*}
    add "Como Parecer Ocupado" to {_titles::*}
    add "Protocolos de Emergência" to {_titles::*}
    add "Como Matar Um Tripulante" to {_titles::*}
    add "Como Matar Um Impostor" to {_titles::*}
    add "Como Sobreviver a Um Impostor" to {_titles::*}
    add "Como Sabotar o Reator" to {_titles::*}
    add "Como Estabilizar o Reator" to {_titles::*}
    add "Comunicação para Engenheiros" to {_titles::*}
    add "Comunicação para Cientistas" to {_titles::*}

    set {_duplicateAmount} to random integer between 1 and 2

    loop {_duplicateAmount} times:

        set {_title} to random element out of {_titles::*}
        remove {_title} from {_titles::*}

        add "%{_title}%" to {library.duplicateTitles.%uuid of {_p}%::*}
        add "%{_title}%" to {library.copy.%uuid of {_p}%::*}

        set {_book} to book named "&e%{_title}%"

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set slot {_slot} of {_inv} to {_book}

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set slot {_slot} of {_inv} to {_book}

        add 1 to {library.duplicates.%uuid of {_p}%}

    set {_amount} to random integer between 10 and 14
    set {_amount} to {_amount} - ({_duplicateAmount} * 2)

    loop {_amount} times:

        set {_title} to random element out of {_titles::*}
        remove {_title} from {_titles::*}

        set {_book} to book named "&e%{_title}%"

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set slot {_slot} of {_inv} to {_book}


    open {_inv} to {_p}

    play sound "minecraft:block.chiseled_bookshelf.insert" with volume 0.5 and pitch 1.2 to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Remover Duplicatas":
        stop

    if click type is left mouse button with shift or right mouse button with shift or double click using mouse:
        cancel event
        stop

    if clicked slot is 22:

        if cursor slot of player is not book:
            cancel event
            stop

        cancel event

        set {_book} to cursor slot of player
        set {_name} to uncolored name of {_book}

        if {library.duplicateTitles.%uuid of player%::*} contains {_name}:

            if amount of cursor slot of player is 2:
                
                close player's inventory

                play sound "minecraft:block.note_block.bass" with volume 1 and pitch 0.6 to player
                play sound "minecraft:block.composter.empty" with volume 0.8 and pitch 0.8 to player

                send "&cSério? Você conseguiu jogar fora AS DUAS CÓPIAS de um livro duplicado."
                stop


            set cursor slot of player to air

            remove {_name} from {library.duplicateTitles.%uuid of player%::*}

            subtract 1 from {library.duplicates.%uuid of player%}

            play sound "minecraft:block.composter.fill_success" with volume 0.8 and pitch 1.2 to player

            if {library.duplicates.%uuid of player%} <= 0:

                wait 2 ticks

                close player's inventory
                advanceTaskStep(player, "remove_duplicate_books")

            stop


        close player's inventory

        play sound "minecraft:block.note_block.bass" with volume 1 and pitch 0.6 to player
        play sound "minecraft:block.composter.empty" with volume 0.8 and pitch 0.8 to player

        if {library.copy.%uuid of player%::*} contains {_name}:
            send "&cSério? Você conseguiu jogar fora AS DUAS CÓPIAS de um livro duplicado."
        else:
            send "&cParabéns. Você acabou de jogar fora o único exemplar. A biblioteca inteira te odeia agora."

        stop

    if clicked slot is 22:
        cancel event
        stop

    if clicked slot is not book:
        if cursor slot of player is not book:
            cancel event
            stop



    if clicked slot is gray stained glass pane:
        cancel event
        stop

    if player is from floodgate:
        wait 1 tick
        set {_item} to player's cursor slot
        if {_item} is air:
            stop
        loop 18 times:
            if slot (loop-number - 1) of event-inventory is air:
                set slot (loop-number - 1) of event-inventory to {_item}
                set player's cursor slot to air

                stop

on inventory close:

    if name of event-inventory is "&8Remover Duplicatas":

        if player's cursor slot is not air:
            set player's cursor slot to air