function start_reactor(p: player, step: number):
    set {reactor.round.%uuid of {_p}%} to 1
    set {reactor.input.%uuid of {_p}%} to 1
    delete {reactor.sequence.%uuid of {_p}%::*}

    loop 5 times:
        add random integer between 0 and 8 to {reactor.sequence.%uuid of {_p}%::*}

    set {_inv} to dropper inventory named "&bIniciar Reator"

    loop 9 times:
        set slot (loop-number - 1) of {_inv} to light gray wool named " "

    open {_inv} to {_p}

    showReactorSequence({_p})

function showReactorSequence(p: player):

    set {reactor.showing.%uuid of {_p}%} to true

    set {_inv} to {_p}'s current inventory

    loop {reactor.round.%uuid of {_p}%} times:

        wait 5 ticks

        set {_slot} to {reactor.sequence.%uuid of {_p}%::%loop-number%}

        set slot {_slot} of {_inv} to blue wool named " "
        play sound "minecraft:block.note_block.pling" with volume 0.7 and pitch 1 to {_p}

        wait 10 ticks

        set slot {_slot} of {_inv} to light gray wool named " "

    delete {reactor.showing.%uuid of {_p}%}
    set {reactor.input.%uuid of {_p}%} to 1

on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&bIniciar Reator":
        stop

    cancel event

    if {reactor.showing.%uuid of player%} is true:
        stop

    set {_expected} to {reactor.sequence.%uuid of player%::%{reactor.input.%uuid of player%}%}

    if clicked slot is {_expected}:

        add 1 to {reactor.input.%uuid of player%}

        play sound "minecraft:block.note_block.pling" with volume 0.7 and pitch 1.4 to player

        set {_inv} to event-inventory

        set slot index of clicked slot of {_inv} to blue wool named " "

        play sound "minecraft:block.note_block.pling" with volume 0.7 and pitch 1.4 to player

        wait 10 ticks

        set slot index of clicked slot of {_inv} to light gray wool named " "



        if {reactor.input.%uuid of player%} > {reactor.round.%uuid of player%}:

            if {reactor.round.%uuid of player%} >= 5:

                reactorSuccess(player)

            else:

                add 1 to {reactor.round.%uuid of player%}

                wait 5 ticks

                showReactorSequence(player)

    else:

        reactorFail(player)

function reactorSuccess(p: player):

    set {_inv} to {_p}'s current inventory

    loop 9 times:
        set slot (loop-number - 1) of {_inv} to lime wool named " "

    play sound "minecraft:entity.player.levelup" with volume 1 and pitch 1.2 to {_p}

    wait 20 ticks

    close {_p}'s inventory

    delete {reactor.sequence.%uuid of {_p}%::*}
    delete {reactor.round.%uuid of {_p}%}
    delete {reactor.input.%uuid of {_p}%}
    delete {reactor.showing.%uuid of {_p}%}

    advanceTaskStep({_p}, "start_reactor")

function reactorFail(p: player):

    set {reactor.showing.%uuid of {_p}%} to true

    set {_inv} to {_p}'s current inventory

    loop 9 times:
        set slot (loop-number - 1) of {_inv} to red wool named " "

    play sound "minecraft:block.note_block.bass" with volume 1 and pitch 0.5 to {_p}

    wait 1 second

    close {_p}'s inventory

    delete {reactor.sequence.%uuid of {_p}%::*}
    delete {reactor.round.%uuid of {_p}%}
    delete {reactor.input.%uuid of {_p}%}
    delete {reactor.showing.%uuid of {_p}%}
    delete {reactor.clickLock.%uuid of {_p}%}

    send "&cMemória de peixe dourado detectada." to {_p}
    send "&cPelo menos explodir o reator exige mais esforço que isso." to {_p}