function trim_plants(p: player, step: number):

    set {_inv} to chest inventory with 6 rows named "&aPodar Planta"
    set {trimPlants.step.%uuid of {_p}%} to {_step}

    loop 31, 40, 49:
        set slot loop-value of {_inv} to stripped birch log named "&6Caule"

    loop 12,13,14,21,22,23,30,32,39,41:
        set slot loop-value of {_inv} to mangrove leaves named "&aFolha"

    set {_possible::*} to 2,3,4,5,6,11,15,20,24,29,33,38,42

    set {_amount} to random integer between 4 and 8

    loop {_amount} times:
        set {_slot} to random element out of {_possible::*}
        remove {_slot} from {_possible::*}

        set slot {_slot} of {_inv} to pale oak leaves named "&6Folha seca"

    open {_inv} to {_p}

on inventory click:

    if holder of event-inventory is set:
        stop
        
    if name of event-inventory is "&aPodar Planta":

        cancel event

        if event-item is air:
            stop

        if event-item is pale oak leaves:

            set slot index of clicked slot of event-inventory to air

            play sound "minecraft:block.azalea_leaves.break" with volume 0.8 and pitch 1.3 to player

            loop 54 times:

                if slot (loop-number - 1) of event-inventory is pale oak leaves:
                    stop

            play sound "minecraft:entity.player.levelup" with volume 0.8 and pitch 1.2 to player

            close player's inventory
            advanceTaskStep(player, "trim_plants", {trimPlants.step.%uuid of player%})
            delete {trimPlants.step.%uuid of player%}
            stop

        if event-item is mangrove leaves:

            play sound "minecraft:block.grass.break" with volume 1 and pitch 0.7 to player
            close player's inventory
            send "&cEra pra podar as folhas secas... não transformar a planta em salada." to player
            stop

        if event-item is stripped birch log:

            play sound "minecraft:block.wood.break" with volume 1 and pitch 0.6 to player
            close player's inventory
            send "&cVocê podou o caule. A planta gostaria de registrar um boletim de ocorrência." to player
            stop

on inventory close:
    if name of event-inventory is "&aPodar Planta":
        wait 1 tick
        if name of player's current inventory is not "&aPodar Planta":
            delete {trimPlants.step.%uuid of player%}