function wash_dishes(p: player, step: number):

    set {_inv} to chest inventory with 5 rows named "&8Lavar Louças"

    delete {dish.detergent.%uuid of {_p}%}
    delete {dish.total.%uuid of {_p}%}
    delete {dish.cleaned.%uuid of {_p}%}


    loop 45 times:
        set slot (loop-number - 1) of {_inv} to gray stained glass pane named " "

    loop 0,1,2,6,7,8,9,10,11,15,16,17:
        set slot loop-value of {_inv} to air

    loop 21,22,23,30,31,32:
        set slot loop-value of {_inv} to blue stained glass pane named "&bÁgua"

    set slot 4 of {_inv} to potion named "&bDetergente"

    set slot 18 of {_inv} to iron bars named " "
    set slot 19 of {_inv} to iron bars named " "
    set slot 20 of {_inv} to iron bars named " "

    set slot 24 of {_inv} to iron bars named " "
    set slot 25 of {_inv} to iron bars named " "
    set slot 26 of {_inv} to iron bars named " "

    set slot 27 of {_inv} to iron bars named " "
    set slot 28 of {_inv} to iron bars named " "
    set slot 29 of {_inv} to iron bars named " "

    set slot 33 of {_inv} to iron bars named " "
    set slot 34 of {_inv} to iron bars named " "
    set slot 35 of {_inv} to iron bars named " "

    set slot 36 of {_inv} to iron bars named " "
    set slot 37 of {_inv} to iron bars named " "
    set slot 38 of {_inv} to iron bars named " "
    set slot 39 of {_inv} to iron bars named " "
    set slot 40 of {_inv} to iron bars named " "
    set slot 41 of {_inv} to iron bars named " "
    set slot 42 of {_inv} to iron bars named " "
    set slot 43 of {_inv} to iron bars named " "
    set slot 44 of {_inv} to iron bars named " "


    set {_slots::*} to 0,1,2,6,7,8,9,10,11,15,16,17

    set {_amount} to random integer between 6 and 10

    set {dish.total.%uuid of {_p}%} to {_amount}
    set {dish.cleaned.%uuid of {_p}%} to 0

    loop {_amount} times:

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set {_type} to random integer between 1 and 5

        if {_type} = 1:
            set {_item} to trident named "&7Garfo Sujo"

        else if {_type} = 2:
            set {_item} to iron shovel named "&7Colher Suja"

        else if {_type} = 3:
            set {_item} to iron sword named "&7Faca Suja"

        else if {_type} = 4:
            set {_item} to bowl named "&7Prato Sujo"

        else:
            set {_item} to bucket named "&7Copo Sujo"

        set slot {_slot} of {_inv} to {_item}

    open {_inv} to {_p}

    play sound "minecraft:block.bubble_column.bubble_pop" with volume 0.6 and pitch 1.3 to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Lavar Louças":
        stop

    if click type is left mouse button with shift or right mouse button with shift or double click using mouse:
        cancel event
        stop

    if clicked slot >= 18:
        cancel event

    if clicked slot is 3 or 5 or 12 or 13 or 14:
        cancel event

    if {dish.detergent.%uuid of player%} is true:
        if clicked slot is 4:
            cancel event
            stop

    if clicked slot is 21 or 22 or 23 or 30 or 31 or 32:

        if player's cursor slot is potion named "&bDetergente":

            cancel event

            set player's cursor slot to air

            set {dish.detergent.%uuid of player%} to true

            loop 21,22,23,30,31,32:
                set slot loop-value of event-inventory to light blue stained glass pane named "&bÁgua com detergente"

            play sound "minecraft:item.bucket.empty" with volume 0.8 and pitch 1.4 to player

            set slot 4 of event-inventory to glass bottle named "&7Frasco de Detergente Vazio"

            stop

        if {dish.detergent.%uuid of player%} is not true:

            play sound "minecraft:block.water.ambient" with volume 0.8 and pitch 1.3 to player
            play sound "minecraft:block.note_block.bass" with volume 0.8 and pitch 1.8 to player
            cancel event
            close player's inventory
            send "&cSe isso funcionasse, ninguém comprava detergente."


            stop

        if player's cursor slot is air:
            cancel event
            stop

        play sound "minecraft:block.bubble_column.bubble_pop" with volume 0.7 and pitch 1.4 to player
        play sound "minecraft:item.bucket.empty" with volume 0.25 and pitch 1.9 to player

        set {_item} to player's cursor slot

        if name of {_item} contains "Limpo":
            cancel event
            stop

        if {_item} is trident item:
            cancel event

            set {_clean} to trident named "&fGarfo Limpo"
            enchant {_clean} with unbreaking 1

            set player's cursor slot to {_clean} with item flags hide enchants

        else if {_item} is iron shovel:
            cancel event

            set {_clean} to iron shovel named "&fColher Limpa"
            enchant {_clean} with unbreaking 1

            set player's cursor slot to {_clean} with item flags hide enchants

        else if {_item} is iron sword:

            cancel event

            set {_clean} to iron sword named "&fFaca Limpa"
            enchant {_clean} with unbreaking 1

            set player's cursor slot to {_clean} with item flags hide enchants

        else if {_item} is bowl:

            cancel event

            set {_clean} to bowl named "&fPrato Limpo"
            enchant {_clean} with unbreaking 1

            set player's cursor slot to {_clean} with item flags hide enchants

        else if {_item} is bucket:

            cancel event

            set {_clean} to bucket named "&fCopo Limpo"
            enchant {_clean} with unbreaking 1

            set player's cursor slot to {_clean} with item flags hide enchants

        play sound "minecraft:block.bubble_column.bubble_pop" with volume 0.7 and pitch 1.8 to player

        stop

    play sound "minecraft:block.decorated_pot.place" with volume 0.35 and pitch 1.5 to player

    wait 1 tick

    set {_clean} to 0

    loop 0,1,2,6,7,8,9,10,11,15,16,17:

        set {_item} to slot loop-value of event-inventory

        if {_item} is air:
            continue

        if name of {_item} contains "Limpo" or "Limpa":
            add 1 to {_clean}

    if {_clean} >= {dish.total.%uuid of player%}:

        close player's inventory
        advanceTaskStep(player, "wash_dishes")


on inventory close:

    if name of event-inventory is "&8Lavar Louças":
        if player's cursor slot is not air:
            set player's cursor slot to air