every 1 second:

    loop all players:

        if biome at loop-player is ice spikes:
            apply slowness 3 to loop-player for 2 seconds

on rightclick:

    if clicked block is not set:
        stop
    # pegar água
    if floor(x-coordinate of clicked block) = 106:
        if floor(z-coordinate of clicked block) = 207:
            if y-coordinate of clicked block < -58:
                cancel event
                if player does not have water bucket:
                    give player water bucket
                    send "&bVocê pegou água!" to player
                    updateCompass(player)
                    stop


on right click:
    if locationKey(location of clicked block) is locationKey(location(90, -59, 236, world("amongmc"))):
        uncancel event


function teste():
    loop all players:
        broadcast "%loop-players's name%: %loop-players's uuid%"


on step on pressure plate:
    if {game.ghosts::*} does not contain player:
        stop

    if locationKey(location of event-block) is "amongmc;88;-59;236":
        teleport player to location(88, -59, 232, world "amongmc")
    else if locationKey(location of event-block) is "amongmc;88;-59;234":
        teleport player to location(88, -59, 238, world "amongmc")