function updateCompass(p: player):
    if {game.state} is "waiting":
        stop
    if {game.impostors::*} does not contain {_p}:   
        if {game.state} is "running":
            set slot 0 of {_p}'s inventory to compass

    # INCÊNDIO

    if {sabotage.lab_fire.active} is true:

        if {_p} has water bucket:

            if block at {lab.fire.1} is fire:
                set {_p}'s compass target to {lab.fire.1}
            else:
                set {_p}'s compass target to {lab.fire.2}

        else:
            set {_p}'s compass target to {water}

        send action bar "&cResolver sabotagem: Incêndio no laboratório" to {_p}
        stop


    
    # LUZES
    

    if {sabotage.lights.active} is true:

        set {_p}'s compass target to {lights.panel}

        send action bar "&eResolver sabotagem: Luzes" to {_p}
        stop


    
    # REATOR
    

    if {sabotage.reactor.active} is true:
        if {sabotage.reactor.leftPressed} is true:
            set {_p}'s compass target to {reactor.right}

        else:
            set {_p}'s compass target to {reactor.left}

        send action bar "&2Resolver sabotagem: Reator" to {_p}
        stop


    
    # TASKS
    
    set {_loc} to getClosestTaskLocation({_p})

    if {_loc} is not set:
        stop

    set compass target of {_p} to {_loc} 

    send action bar "&bBússola apontando para sua task mais próxima" to {_p}