
# SABOTAGENS - INÍCIO


function startLabFire():

    set {sabotage.lab_fire.active} to true
    set {sabotage.lab_fire.progress} to 0
    set {sabotage.lab_fire.remaining} to {config.labFireTime}

    set {lab.fire.1} to location(116, -58, 252, world("amongmc"))
    set {lab.fire.2} to location(122, -59, 245, world("amongmc"))

    set block at {lab.fire.1} to fire
    set block at {lab.fire.2} to fire

    set {water} to location(106, -59, 207, world("amongmc"))

    loop all players:
        updateCompass(loop-player)
        updateScoreboard(loop-player)


function startLightsSabotage():

    set {sabotage.lights.active} to true

    loop 5 times:
        set {_n} to random integer between 1 and 5
        set {_z} to 206 - {_n} + 1
        execute console command "setblock 129 -58 %{_z}% minecraft:lever[face=wall,facing=west,powered=true]"

    set {lights.panel} to location(129, -58, 204, world("amongmc"))

    loop all players:
        updateInventory(loop-player)
        updateScoreboard(loop-player)

        if loop-player is not in {game.impostors::*}:
            execute console command "effect give %loop-player% minecraft:blindness infinite 0 true"


function startReactorSabotage():

    set {sabotage.reactor.active} to true
    set {sabotage.reactor.leftPressed} to false
    set {sabotage.reactor.rightPressed} to false
    set {sabotage.reactor.remaining} to {config.reactorCollapseTime}

    set {reactor.left} to location(116, -60, 242, world("amongmc"))
    set {reactor.right} to location(125, -60, 203, world("amongmc"))
    set {reactor.center} to location(122, -58, 239, world("amongmc"))

    loop all players:
        updateCompass(loop-player)
        updateScoreboard(loop-player)


function startDoorSabotage():

    set {sabotage.doors.active} to true

    play sound "minecraft:block.iron_door.close" with volume 0.8 and pitch 0.9 to all players

    loop {doorCount} times:
        animateDoor({doors::%loop-number%::*}, true)

    set {_waittime} to "%{config.doorDuration}% seconds" parsed as timespan
    wait {_waittime}
    
    if {game.state} is "meeting":
        stop

    play sound "minecraft:block.iron_door.close" with volume 0.8 and pitch 0.9 to all players

    loop {doorCount} times:
        animateDoor({doors::%loop-number%::*}, false)

    set {sabotage.doors.active} to false
    startSabotageCooldown({config.doorCooldown})



# SABOTAGENS - FINALIZAÇÃO


function finishLightsSabotage():

    set {sabotage.lights.active} to false

    loop 5 times:
        set {_z} to 206 - loop-number + 1
        execute console command "setblock 129 -58 %{_z}% minecraft:lever[face=wall,facing=west,powered=false]"

    delete {lights.panel}

    loop all players:
        execute console command "effect clear %loop-player% minecraft:blindness"
        updateCompass(loop-player)
        updateScoreboard(loop-player)

    send "&aLuzes restauradas!" to all players
    startSabotageCooldown({config.sabotageCooldown})


function finishLabFire():

    set {sabotage.lab_fire.active} to false

    delete {lab.fire.1}
    delete {lab.fire.2}
    delete {sabotage.lab_fire.remaining}

    loop all players:
        remove water bucket from loop-player

    send "&aSabotagem resolvida!" to all players
    startSabotageCooldown({config.sabotageCooldown})


function finishReactorSabotage():

    set {sabotage.reactor.active} to false
    delete {sabotage.reactor.remaining}
    delete {reactor.left}
    delete {reactor.right}
    delete {reactor.center}

    startSabotageCooldown({config.sabotageCooldown})

    loop all players:
        updateCompass(loop-player)
        updateScoreboard(loop-player)

    send "&aReator estabilizado!" to all players



# SABOTAGEM - UTILITÁRIOS


function startSabotageCooldown(seconds: number):

    set {sabotage.cooldownRemaining} to {_seconds}

    loop all players:
        updateCompass(loop-player)
        updateScoreboard(loop-player)


function setLights(state: boolean):

    loop 5 times:
        set {_z} to 206 - loop-number + 1

        if {_state} is true:
            execute console command "setblock 129 -58 %{_z}% minecraft:lever[face=wall,facing=west,powered=true]"
        else:
            execute console command "setblock 129 -58 %{_z}% minecraft:lever[face=wall,facing=west,powered=false]"


function checkLights():

    loop 5 times:
        set {_z} to 206 - loop-number + 1
        set {_loc} to location(130, -58, {_z}, world("amongmc"))

        if block at {_loc} is redstone powered:
            stop

    finishLightsSabotage()


function animateDoor(blocks: objects, close: boolean):

    set {_a} to {_blocks::1}
    set {_b} to {_blocks::2}
    set {_c} to {_blocks::3}

    if {_close} is true:

        set block 3 above {_a} to netherite block
        set block above {_c} to netherite block

        wait 3 ticks

        set block 2 above {_a} to netherite block
        set block 2 above {_c} to netherite block
        set block above {_b} to netherite block
        set block 3 above {_b} to netherite block

        wait 3 ticks

        set block above {_a} to netherite block
        set block 3 above {_c} to netherite block
        set block 2 above {_b} to netherite block

    else:
        set block above {_a} to air
        set block 3 above {_c} to air
        set block 2 above {_b} to air 

        wait 3 ticks

        set block 2 above {_a} to air 
        set block 2 above {_c} to air 
        set block above {_b} to air 
        set block 3 above {_b} to air 

        wait 3 ticks

        set block 3 above {_a} to air 
        set block above {_c} to air 




every 1 second:

    if {game.state} is not "running":
        stop

    if {sabotage.reactor.remaining} is not set:
        stop

    remove 1 from {sabotage.reactor.remaining}
    loop all players:
        updateScoreboard(loop-player)

    if {sabotage.reactor.remaining} <= 0:
        delete {sabotage.reactor.remaining}

        broadcast "&4O reator entrou em colapso!"
        endGame("impostors")

every 1 second:

    if {game.state} is not "running":
        stop

    if {sabotage.lab_fire.remaining} is not set:
        stop

    remove 1 from {sabotage.lab_fire.remaining}
    loop all players:
        updateScoreboard(loop-player)

    if {sabotage.lab_fire.remaining} <= 0:
        delete {sabotage.lab_fire.remaining}

        broadcast "&cO laboratório foi consumido pelo incêndio!"
        endGame("impostors")

every 1 second:

    set {_min} to 1
    if {sabotage.cooldownRemaining} > 0:
        set {_min} to {sabotage.cooldownRemaining}
        remove 1 from {sabotage.cooldownRemaining}


    loop {game.impostors::*}:
        if {vent.active.%uuid of loop-value%} is true:
            continue
        if {game.state} is "running":
            set slot 0 of loop-value's inventory to {_min} of compass named "&cIncendiar laboratório"
            set slot 1 of loop-value's inventory to {_min} of compass named "&8Trancar portas"
            set slot 2 of loop-value's inventory to {_min} of compass named "&eApagar luzes"
            set slot 3 of loop-value's inventory to {_min} of compass named "&2Sobrecarregar reator"



    if {sabotage.lab_fire.active} is true:
        loop all players:
            drawTaskParticles(loop-player, {water})
            play sound "block.beacon.deactivate" with volume 2 and pitch 0.5 to loop-player
            play sound "block.note_block.bell" with volume 0.7 and pitch 0.8 to loop-player



    if {sabotage.lights.active} is true:
        loop all players:
            drawTaskParticles(loop-player, {lights.panel})


    if {sabotage.reactor.active} is true:

        loop all players:
            drawTaskParticles(loop-player, {reactor.left})
            drawTaskParticles(loop-player, {reactor.right})
            play sound "block.beacon.deactivate" with volume 2 and pitch 0.5 to loop-player

        draw 10 of smoke at {reactor.center} with offset vector 1,1.5,1
        draw 8 of electric_spark at {reactor.center} with offset vector 0.8,0.8,0.8
        draw 4 of lava at {reactor.center} with offset vector 0.5,0.5,0.5
        draw 6 of ash at {reactor.center} with offset vector 1,1.5,1


on step on pressure plate:

    if {sabotage.reactor.active} is not true:
        stop

    if block at {reactor.left} is redstone powered:
        set {sabotage.reactor.leftPressed} to true
    else:
        set {sabotage.reactor.leftPressed} to false

    if block at {reactor.right} is redstone powered:
        set {sabotage.reactor.rightPressed} to true
    else:
        set {sabotage.reactor.rightPressed} to false

    if {sabotage.reactor.leftPressed} is true:
        if {sabotage.reactor.rightPressed} is true:
            finishReactorSabotage()

    loop all players:
        updateCompass(loop-player)


on load:

    delete {doorMarkers::*}
    delete {ventMarkers::*}
    delete {doors::*}
    delete {doorCount}


    loop 55 times:
        set {_x} to 75 + loop-number

        loop 70 times:
            set {_z} to 190 + loop-number-2


            set {_loc} to location({_x} + 0.5, -60, {_z} + 0.5, world("amongmc"))

            if block at {_loc} is iron trapdoor:
                add {_loc} to {ventMarkers::*}

            if block at {_loc} is not netherite block:
                continue

            add {_loc} to {doorMarkers::*}


            set {_left} to location({_x} - 1 + 0.5, -60, {_z} + 0.5, world("amongmc"))

            if block at {_left} is not netherite block:

                set {_mid} to location({_x} + 1 + 0.5, -60, {_z} + 0.5, world("amongmc"))
                set {_right} to location({_x} + 2 + 0.5, -60, {_z} + 0.5, world("amongmc"))

                if block at {_mid} is netherite block:
                    if block at {_right} is netherite block:

                        add 1 to {doorCount}

                        set {doors::%{doorCount}%::1} to {_loc}
                        set {doors::%{doorCount}%::2} to {_mid}
                        set {doors::%{doorCount}%::3} to {_right}

                        continue


            set {_back} to location({_x} + 0.5, -60, {_z} - 1 + 0.5, world("amongmc"))

            if block at {_back} is not netherite block:

                set {_mid} to location({_x} + 0.5, -60, {_z} + 1 + 0.5, world("amongmc"))
                set {_front} to location({_x} + 0.5, -60, {_z} + 2 + 0.5, world("amongmc"))

                if block at {_mid} is netherite block:
                    if block at {_front} is netherite block:

                        add 1 to {doorCount}

                        set {doors::%{doorCount}%::1} to {_loc}
                        set {doors::%{doorCount}%::2} to {_mid}
                        set {doors::%{doorCount}%::3} to {_front}


    loop 55 times:
        set {_x} to 75 + loop-number

        loop 70 times:
            set {_z} to 190 + loop-number-2

            set {_loc} to location({_x} + 0.5, -61, {_z} + 0.5, world("amongmc"))

            if block at {_loc} is iron trapdoor:
                add {_loc} to {ventMarkers::*}


on right click:

    if {game.impostors::*} contains player:
        if player's tool is compass:

            # LAB FIRE
            if name of player's tool is "&cIncendiar laboratório":

                if {sabotage.cooldownRemaining} > 0:
                    send "&cSabotagem em cooldown!" to player
                    stop
                if {sabotage.lab_fire.active} is true:
                    stop
                if {sabotage.doors.active} is true:
                    stop
                if {sabotage.lights.active} is true:
                    stop

                startLabFire()
                send "&cVocê iniciou a sabotagem!" to player
                stop

            # DOORS
            if name of player's tool is "&8Trancar portas":

                if {sabotage.cooldownRemaining} > 0:
                    send "&cSabotagem em cooldown!" to player
                    stop
                if {sabotage.lab_fire.active} is true:
                    stop
                if {sabotage.doors.active} is true:
                    stop
                if {sabotage.lights.active} is true:
                    stop

                startDoorSabotage()
                send "&cVocê trancou todas as portas!" to player
                stop

            # LIGHTS
            if name of player's tool is "&eApagar luzes":

                if {sabotage.cooldownRemaining} > 0:
                    send "&cSabotagem em cooldown!" to player
                    stop
                if {sabotage.lab_fire.active} is true:
                    stop
                if {sabotage.doors.active} is true:
                    stop
                if {sabotage.lights.active} is true:
                    stop

                startLightsSabotage()
                send "&eVocê sabotou as luzes!" to player
                stop

            # REACTOR
            if name of player's tool is "&2Sobrecarregar reator":

                if {sabotage.cooldownRemaining} > 0:
                    send "&cSabotagem em cooldown!" to player
                    stop
                if {sabotage.lab_fire.active} is true:
                    stop
                if {sabotage.lights.active} is true:
                    stop
                if {sabotage.doors.active} is true:
                    stop
                if {sabotage.reactor.active} is true:
                    stop

                startReactorSabotage()
                send "&2Você iniciou a sobrecarga do reator!" to player


    if clicked block is lever:
        if floor(x-coordinate of location of clicked block) = 129:
            if floor(y-coordinate of location of clicked block) = -58:
                if floor(z-coordinate of location of clicked block) >= 202:
                    if floor(z-coordinate of location of clicked block) <= 206:

                        if {sabotage.lights.active} is not true:
                            cancel event
                            stop

                        wait 1 tick
                        checkLights()
                        stop


    if player is holding water bucket:
        if player's gamemode is not creative:
            cancel event
        if {game.ghosts::*} contains player:
            stop
        if clicked block is fire:

            remove 1 water bucket from player
            set block at location of clicked block to air

            add 1 to {sabotage.lab_fire.progress}

            send "&aFogo apagado!" to player

            if {sabotage.lab_fire.progress} = 2:
                finishLabFire()
            updateCompass(player)