function updateArmor(p: player):

    set {_color} to {color.%uuid of {_p}%}

    if {_color} is not set:
        set {_color} to "white"

    if {_color} is "white":
        set {_rgb} to rgb(249, 255, 254)
    else if {_color} is "orange":
        set {_rgb} to rgb(249, 128, 29)
    else if {_color} is "magenta":
        set {_rgb} to rgb(199, 78, 189)
    else if {_color} is "light_blue":
        set {_rgb} to rgb(58, 179, 218)
    else if {_color} is "yellow":
        set {_rgb} to rgb(254, 216, 61)
    else if {_color} is "lime":
        set {_rgb} to rgb(128, 199, 31)
    else if {_color} is "pink":
        set {_rgb} to rgb(243, 139, 170)
    else if {_color} is "gray":
        set {_rgb} to rgb(71, 79, 82)
    else if {_color} is "light_gray":
        set {_rgb} to rgb(157, 157, 151)
    else if {_color} is "cyan":
        set {_rgb} to rgb(22, 156, 156)
    else if {_color} is "purple":
        set {_rgb} to rgb(137, 50, 184)
    else if {_color} is "blue":
        set {_rgb} to rgb(60, 68, 170)
    else if {_color} is "brown":
        set {_rgb} to rgb(131, 84, 50)
    else if {_color} is "green":
        set {_rgb} to rgb(94, 124, 22)
    else if {_color} is "red":
        set {_rgb} to rgb(176, 46, 38)
    else if {_color} is "black":
        set {_rgb} to rgb(29, 29, 33)

    # Capacete padrão
    set {_helmet} to leather helmet
    dye {_helmet} {_rgb}

    # Chapéu personalizado
    if {hat.%uuid of {_p}%} is "none":
        set {_helmet} to air
    else if {hat.%uuid of {_p}%} is set:
        set {_helmet} to {hat.%uuid of {_p}%}

    set {_chestplate} to leather chestplate
    dye {_chestplate} {_rgb}

    set {_leggings} to leather leggings
    dye {_leggings} {_rgb}

    set {_boots} to leather boots
    dye {_boots} {_rgb}

    equip {_p} with {_helmet}, {_chestplate}, {_leggings}, {_boots}

command /cor:
    aliases: color
    trigger:
        if {game.state} is not "waiting":
            send "&cVocê não pode mudar sua cor agora!" to player
            stop
            
        set {_inv} to chest inventory with 2 rows named "&8Escolha sua cor"

        if colorTaken("white", player) is true:
            set slot 0 of {_inv} to white stained glass named "&fBranco"
        else:
            set slot 0 of {_inv} to white wool named "&fBranco"

        if colorTaken("orange", player) is true:
            set slot 1 of {_inv} to orange stained glass named "&6Laranja"
        else:
            set slot 1 of {_inv} to orange wool named "&6Laranja"

        if colorTaken("magenta", player) is true:
            set slot 2 of {_inv} to magenta stained glass named "&dMagenta"
        else:
            set slot 2 of {_inv} to magenta wool named "&dMagenta"

        if colorTaken("light_blue", player) is true:
            set slot 3 of {_inv} to light blue stained glass named "&bAzul Claro"
        else:
            set slot 3 of {_inv} to light blue wool named "&bAzul Claro"

        if colorTaken("yellow", player) is true:
            set slot 4 of {_inv} to yellow stained glass named "&eAmarelo"
        else:
            set slot 4 of {_inv} to yellow wool named "&eAmarelo"

        if colorTaken("lime", player) is true:
            set slot 5 of {_inv} to lime stained glass named "&aVerde Limão"
        else:
            set slot 5 of {_inv} to lime wool named "&aVerde Limão"

        if colorTaken("pink", player) is true:
            set slot 6 of {_inv} to pink stained glass named "&dRosa"
        else:
            set slot 6 of {_inv} to pink wool named "&dRosa"

        if colorTaken("gray", player) is true:
            set slot 7 of {_inv} to gray stained glass named "&8Cinza"
        else:
            set slot 7 of {_inv} to gray wool named "&8Cinza"

        if colorTaken("light_gray", player) is true:
            set slot 8 of {_inv} to light gray stained glass named "&7Cinza Claro"
        else:
            set slot 8 of {_inv} to light gray wool named "&7Cinza Claro"

        if colorTaken("cyan", player) is true:
            set slot 9 of {_inv} to cyan stained glass named "&3Ciano"
        else:
            set slot 9 of {_inv} to cyan wool named "&3Ciano"

        if colorTaken("purple", player) is true:
            set slot 10 of {_inv} to purple stained glass named "&5Roxo"
        else:
            set slot 10 of {_inv} to purple wool named "&5Roxo"

        if colorTaken("blue", player) is true:
            set slot 11 of {_inv} to blue stained glass named "&9Azul"
        else:
            set slot 11 of {_inv} to blue wool named "&9Azul"

        if colorTaken("brown", player) is true:
            set slot 12 of {_inv} to brown stained glass named "&6Marrom"
        else:
            set slot 12 of {_inv} to brown wool named "&6Marrom"

        if colorTaken("green", player) is true:
            set slot 13 of {_inv} to green stained glass named "&2Verde"
        else:
            set slot 13 of {_inv} to green wool named "&2Verde"

        if colorTaken("red", player) is true:
            set slot 14 of {_inv} to red stained glass named "&cVermelho"
        else:
            set slot 14 of {_inv} to red wool named "&cVermelho"

        if colorTaken("black", player) is true:
            set slot 15 of {_inv} to black stained glass named "&0Preto"
        else:
            set slot 15 of {_inv} to black wool named "&0Preto"

        open {_inv} to player

on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Escolha sua cor":
        stop

    cancel event

    if clicked slot < 0:
        stop

    if clicked slot > 15:
        stop

    if clicked slot = 0:
        set {_color} to "white"
    else if clicked slot = 1:
        set {_color} to "orange"
    else if clicked slot = 2:
        set {_color} to "magenta"
    else if clicked slot = 3:
        set {_color} to "light_blue"
    else if clicked slot = 4:
        set {_color} to "yellow"
    else if clicked slot = 5:
        set {_color} to "lime"
    else if clicked slot = 6:
        set {_color} to "pink"
    else if clicked slot = 7:
        set {_color} to "gray"
    else if clicked slot = 8:
        set {_color} to "light_gray"
    else if clicked slot = 9:
        set {_color} to "cyan"
    else if clicked slot = 10:
        set {_color} to "purple"
    else if clicked slot = 11:
        set {_color} to "blue"
    else if clicked slot = 12:
        set {_color} to "brown"
    else if clicked slot = 13:
        set {_color} to "green"
    else if clicked slot = 14:
        set {_color} to "red"
    else if clicked slot = 15:
        set {_color} to "black"

    if {color.%uuid of player%} is {_color}:
        send "&eVocê já está usando essa cor." to player
        stop

    loop all players:
        if loop-player is not player:
            if {color.%uuid of loop-player%} is {_color}:
                send "&cEssa cor já está sendo utilizada por outro jogador." to player
                stop

    set {color.%uuid of player%} to {_color}

    close player's inventory
    updateArmor(player)
    send "&aSua cor agora é &f%{_color}%&a."

function colorTaken(color: text, viewer: player) :: boolean:

    loop all players:
        if {color.%uuid of loop-player%} is {_color}:
            return true

    return false

function chatColor(p: player) :: text:

    set {_color} to {color.%uuid of {_p}%}

    if {_color} is "white":
        return "&f"
    else if {_color} is "orange":
        return "&6"
    else if {_color} is "magenta":
        return "&d"
    else if {_color} is "light_blue":
        return "&b"
    else if {_color} is "yellow":
        return "&e"
    else if {_color} is "lime":
        return "&a"
    else if {_color} is "pink":
        return "&d"
    else if {_color} is "gray":
        return "&8"
    else if {_color} is "light_gray":
        return "&7"
    else if {_color} is "cyan":
        return "&3"
    else if {_color} is "purple":
        return "&5"
    else if {_color} is "blue":
        return "&9"
    else if {_color} is "brown":
        return "&6"
    else if {_color} is "green":
        return "&2"
    else if {_color} is "red":
        return "&c"
    else if {_color} is "black":
        return "&0"

    return "&f"

on right click:

    if player's tool is nether star named "&eEscolher cor":
        cancel event
        execute player command "cor"

on join:
    set {_ok} to false

    if {color.%uuid of player%} is set:

        set {_myColor} to {color.%uuid of player%}
        set {_taken} to false

        loop all players:
            if loop-player is not player:
                if {color.%uuid of loop-player%} is {_myColor}:
                    set {_taken} to true

        if {_taken} is false:
            set {_ok} to true

    if {_ok} is false:

        loop "white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black":

            set {_taken} to false

            loop all players:
                if loop-player is not player:
                    if {color.%uuid of loop-player%} is loop-value-1:
                        set {_taken} to true

            if {_taken} is false:

                set {color.%uuid of player%} to loop-value

                send "&eVocê não tinha uma cor, ou ela já está sendo usada por outro jogador." to player
                send "&7Sua nova cor é %chatColor(player)%%loop-value%&7." to player
                send "&7Você pode alterá-la usando a estrela do nether ou digitando &f/cor&7." to player
                stop


    updateArmor(player)