function resetGame():

    set {game.state} to "waiting"
    execute console command "team empty players"
    updateCall()

    delete {game.completedTasks}
    delete {game.totalTasks}

    delete {game.impostors::*}
    delete {game.crewmates::*}
    delete {game.ghosts::*}

    if {game.session} is not set:
        set {game.session} to 0

    add 1 to {game.session}

    execute console command "kill @e[type=minecraft:armor_stand,tag=among_body]"

    loop all players:
        delete {playerTasks.%uuid of loop-player%::*}
        delete {playerTasksDone.%uuid of loop-player%::*}
        delete {playerTaskStep.%uuid of loop-player%::*}
        delete {openTask.%uuid of loop-player%}
        delete {playerTaskProgress.%uuid of loop-player%::*}
        delete {playerTaskDone.%uuid of loop-player%::*}
        delete {reagent.ready.%uuid of loop-player%}
        delete {reagent.processing.%uuid of loop-player%}
        
        close loop-player's inventory 

    delete {sabotage.pause}

    delete {sabotage.cooldownRemaining}

    delete {sabotage.lab_fire.progress}
    delete {sabotage.lab_fire.cooldown}
    delete {sabotage.lab_fire.remaining}

    delete {sabotage.reactor.remaining}

    set {sabotage.lab_fire.active} to false
    set {sabotage.reactor.active} to false
    set {sabotage.lights.active} to false
    set {sabotage.doors.active} to false

    if {lab.fire.1} is set:
        set block at {lab.fire.1} to air

    if {lab.fire.2} is set:
        set block at {lab.fire.2} to air

    delete {lab.fire.1}
    delete {lab.fire.2}

    loop 5 times:
        set {_z} to 206 - loop-number + 1
        execute console command "setblock 129 -58 %{_z}% minecraft:lever[face=wall,facing=west,powered=false]"

    delete {reactor.left}
    delete {reactor.right}
    delete {reactor.center}

    delete {sabotage.reactor.leftPressed}
    delete {sabotage.reactor.rightPressed}

    delete {meeting.cooldown.remaining}

    loop all players:
        delete {meeting.callsLeft.%uuid of loop-player%}
        delete {vote.%uuid of loop-player%}
        delete {voteSlot.%uuid of loop-player%::*}
        delete {votes.%uuid of loop-player%}

    delete {votes.skip}

    delete {killCooldown::*}
    
    loop {doorMarkers::*}:
        set block above loop-value to air
        set block 2 above loop-value to air
        set block 3 above loop-value to air

    set {sabotage.doors.active} to false

    loop all players:

        clear inventory of loop-player

        execute console command "effect clear %loop-player% minecraft:blindness"

        reveal loop-player to all players

        clearScoreboard(loop-player)
        updateCompass(loop-player)
        updateArmor(loop-player)
        updateSpeed(loop-player)

        delete {killCooldown.%uuid of loop-player%}
        delete {vent.active.%uuid of loop-player%}
        delete {vent.index.%uuid of loop-player%}

    

command /end:
    aliases: parar
    permission: op
    trigger:

        resetGame()

        send "&cJogo encerrado!" to all players

        loop all players:
            teleport loop-player to location(118.5, -58.5, 281.5, world("amongmc"))
            updateInventory(loop-player)
            updateArmor(loop-player)
            updateScoreboard(loop-player)


command /start:
    aliases: comecar
    permission: op
    trigger:

        resetGame()


        loop all players:
            add loop-player to {game.crewmates::*}

            execute console command "title %loop-player% times 0 20 5"
            execute console command "title %loop-player% title {""text"":""3"",""color"":""yellow""}"

        wait 1 second

        loop all players:
            execute console command "title %loop-player% times 0 20 5"
            execute console command "title %loop-player% title {""text"":""2"",""color"":""gold""}"

        wait 1 second

        loop all players:
            execute console command "title %loop-player% times 0 20 5"
            execute console command "title %loop-player% title {""text"":""1"",""color"":""red""}"

        wait 1 second

        set {game.state} to "running"
        updateCall()
        execute console command "team join players @a"
        
        set {_count} to {config.impostors}
        set {_players} to size of all players

        if {_players} <= 6:
            set {_max} to 1
        else if {_players} <= 9:
            set {_max} to 2
        else:
            set {_max} to 3

        if {_count} > {_max}:
            broadcast "&eAtenção! Como há apenas %{_players}% jogadores, o número de impostores foi limitado para %{_max}%."
            set {_count} to {_max}

        loop {_count} times:
            set {_p} to random element out of {game.crewmates::*}

            remove {_p} from {game.crewmates::*}
            add {_p} to {game.impostors::*}

        loop all players:

            assignTasks(loop-player)

            add size of {playerTasks.%uuid of loop-player%::*} to {game.totalTasks}

        loop all players:

            clearScoreboard(loop-player)
            updateScoreboard(loop-player)
            updateCompass(loop-player)

        teleportMeeting()

        loop {game.impostors::*}:

            execute console command "title %loop-value% times 10 20 5"
            execute console command "title %loop-value% title {""text"":""IMPOSTOR"",""bold"":true,""color"":""dark_red""}"
            execute console command "title %loop-value% subtitle {""text"":""Elimine a tripulação"",""color"":""gray""}"

            play sound "block.beacon.activate" with volume 1 and pitch 0.7 to loop-value
            play sound "entity.warden.nearby_close" with volume 1 and pitch 0.8 to loop-value

            send "" to loop-value
            send "&8&m----------------------------------------" to loop-value
            send "&cVocê é o &4&lIMPOSTOR&c!" to loop-value
            send "&7Elimine a tripulação antes que completem as tarefas." to loop-value
            send "&7Use &eShift&7 sobre uma vent para entrar nela." to loop-value
            send "&7Sabote sistemas para criar oportunidades." to loop-value
            send "&8&m----------------------------------------" to loop-value

        loop {game.crewmates::*}:

            execute console command "title %loop-value% times 10 20 5"
            execute console command "title %loop-value% title {""text"":""CREWMATE"",""bold"":true,""color"":""aqua""}"
            execute console command "title %loop-value% subtitle {""text"":""Complete suas tarefas"",""color"":""gray""}"

            play sound "entity.player.levelup" with volume 1 and pitch 0.8 to loop-value
            play sound "block.beacon.activate" with volume 1 and pitch 1.2 to loop-value

            send "" to loop-value
            send "&8&m----------------------------------------" to loop-value
            send "&bVocê é um &3&lCREWMATE&b!" to loop-value
            send "&7Complete todas as tarefas." to loop-value
            send "&7Reporte corpos encontrados." to loop-value
            send "&7Use reuniões para descobrir os impostores." to loop-value
            send "&8&m----------------------------------------" to loop-value

        loop all players:
            set {meeting.callsLeft.%uuid of loop-player%} to {config.meetingLimit}
        startKillCooldown({config.initialKillCooldown})
        startSabotageCooldown({config.initialSabotageCooldown})
        set {meeting.cooldown.remaining} to {config.initialMeetingCooldown}

function checkEndGame():

    #parar de encerrar o jogo. Apenas pra debugging:

    #stop


    if {game.state} is "waiting":
        stop

    set {_alive} to 0
    set {_aliveImpostors} to 0

    loop all players:

        if {game.ghosts::*} contains loop-player:
            continue

        if {game.impostors::*} contains loop-player:
            add 1 to {_aliveImpostors}
        else:
            add 1 to {_alive}

    if {_aliveImpostors} = 0:
        endGame("crewmates")
        stop

    if {_alive} <= {_aliveImpostors}:
        endGame("impostors")
        stop

    if {game.completedTasks} >= {game.totalTasks}:
        endGame("crewmates")
        stop


function endGame(winner: text):
    if {game.state} is "waiting" or "ending":
        stop
    set {game.state} to "ending"
    
    
    
    loop all players:
        close loop-player's inventory

        play sound "minecraft:ui.toast.challenge_complete" with volume 0.7 and pitch 1 to loop-player

    if {_winner} is "crewmates":

        loop all players:

            if {game.impostors::*} contains loop-player:
                execute console command "title %loop-player% title {""text"":""DERROTA"",""color"":""red"",""bold"":true}"
                execute console command "title %loop-player% subtitle {""text"":""Os Crewmates venceram!"",""color"":""gray""}"
            else:
                execute console command "title %loop-player% title {""text"":""VITÓRIA"",""color"":""aqua"",""bold"":true}"
                execute console command "title %loop-player% subtitle {""text"":""Os Crewmates venceram!"",""color"":""gray""}"

    else:

        loop all players:

            if {game.impostors::*} contains loop-player:
                execute console command "title %loop-player% title {""text"":""VITÓRIA"",""color"":""red"",""bold"":true}"
                execute console command "title %loop-player% subtitle {""text"":""Os Impostores venceram!"",""color"":""gray""}"
            else:
                execute console command "title %loop-player% title {""text"":""DERROTA"",""color"":""aqua"",""bold"":true}"
                execute console command "title %loop-player% subtitle {""text"":""Os Impostores venceram!"",""color"":""gray""}"

    broadcast ""
    broadcast "&6========== Fim de Jogo =========="

    if {_winner} is "crewmates":
        broadcast "&bOs Crewmates venceram!"
    else:
        broadcast "&cOs Impostores venceram!"

    broadcast ""
    broadcast "&7Impostores:"

    loop {game.impostors::*}:
        broadcast " &c• %loop-value%"

    broadcast ""

    wait 6 seconds

    execute console command "end"



function updateInventory(p: player):
    wait 1 tick
    clear {_p}'s inventory
    wait 1 tick
    if {game.state} is "meeting":
        if {game.ghosts::*} does not contain {_p}:
            set {_item} to book named "&eVotar"
            set lore of {_item} to "&7Clique com botão direito para votar"
            set slot 4 of {_p}'s inventory to {_item}
    updateCompass({_p})
    updateArmor({_p})
    if {vent.active.%uuid of {_p}%} is true:
        set slot 6 of {_p} to compass named "&eVent anterior"
        set slot 7 of {_p} to ender pearl named "&aSair da vent"
        set slot 8 of {_p} to compass named "&ePróxima vent"
    if {game.state} is "waiting":
        set slot 0 of {_p}'s inventory to nether star named "&eEscolher cor"
        set slot 1 of {_p}'s inventory to turtle helmet named "&dEscolher chapéu"
        if {_p} is op:
            set slot 2 of {_p}'s inventory to compass named "&cConfigurações"


on load:
    if {game.state} is not set:
        set {game.state} to "waiting"


on step on pressure plate:
    if {game.ghosts::*} contains player:
        cancel event 


on inventory click:
    if player's gamemode is creative:
        stop
    if clicked inventory is player's inventory:
        cancel event
    else if click type is number key:
        cancel event
    if holder of event-inventory is set:
        cancel event
    

on swap hand items:
    if player's gamemode is not creative:
        cancel event

on drop:
    if player's gamemode is not creative:
        cancel event
        updateInventory(player)

on damage:
    if attacker's gamemode is creative:
        stop
    if victim is item frame:
        cancel event
    if victim is painting:
        cancel event
    
on food level change:
    cancel event
    set food level of player to 2

on right click:
    if player's gamemode is creative:
        stop
    if clicked entity is glow item frame:
        cancel event
    if clicked entity is item frame:
        cancel event
    if "%type of clicked block%" starts with "potted":
        cancel event
    if clicked block is brewing stand:
        cancel event
    if "%type of clicked block%" end with "trapdoor":
        cancel event
    if "%type of clicked block%" end with "shelf":
        cancel event
    if clicked block is lever:
        if {game.ghosts::*} contains player:
            cancel event

on command "op":
    if {game.state} is "waiting":
        loop all players:
            updateInventory(loop-player)

on command "deop":
    if {game.state} is "waiting":
        loop all players:
            updateInventory(loop-player)


