define new bot named "Bot":
    token: {bot.token}
    intents: default intents
    policy: all
    auto reconnect: true

discord command link <text>:
    prefixes: !
    trigger:

        if arg-1 is not set:
            reply with "Uso: !link <nickname>"
            stop

        set {_nick} to arg-1 in lower case
        set {_id} to discord id of event-user

        set {_oldNick} to {discord.link.nick.%{_id}%}

        delete {discord.link.discord.%{_oldNick}%}

        set {_oldId} to {discord.link.discord.%{_nick}%}

        delete {discord.link.nick.%{_oldId}%}

        set {discord.link.discord.%{_nick}%} to {_id}
        set {discord.link.nick.%{_id}%} to {_nick}

        reply with "✔ Vinculado ao nick %{_nick}%"

discord command check:
    prefixes: !
    trigger:
        reply with "%{discord.link.nick.%discord id of event-user%}%"

command /discordid:
    trigger:
        set {_id} to {discord.link.discord.%name of player in lower case%}

        if {_id} is not set:
            send "&cVocê não possui um Discord vinculado."
            stop

        send "&aSeu ID do Discord é: &f%{_id}%"

function muteAll():

    set {_call} to voice channel with id {bot.call}
    set {_guild} to guild with id {bot.guild}

    loop all players:

        set {_id} to {discord.link.discord.%name of loop-player in lowercase%}
        if {_id} is not set:
            continue

        set {_user} to member with id {_id} in {_guild}

        if voice channel of {_user} is not {_call}:
            continue

        voice mute {_user}


function muteDead():

    set {_call} to voice channel with id "1522820042658549853"
    set {_guild} to guild with id "1522820041744318465"

    loop all players:

        set {_id} to {discord.link.discord.%name of loop-player in lowercase%}
        if {_id} is not set:
            continue

        set {_user} to member with id {_id} in {_guild}

        if voice channel of {_user} is not {_call}:
            continue

        if {game.ghosts::*} contains loop-player:
            voice mute {_user}
        else:
            unmute member {_user}


function unmuteAll():

    set {_call} to voice channel with id "1522820042658549853"
    set {_guild} to guild with id "1522820041744318465"

    loop all players:

        set {_id} to {discord.link.discord.%name of loop-player in lowercase%}
        if {_id} is not set:
            continue

        set {_user} to member with id {_id} in {_guild}

        if voice channel of {_user} is not {_call}:
            continue

        unmute member {_user}



function updateCall():
    if {game.state} is "waiting":
        unmuteAll()
    else if {game.state} is "running":
        muteAll()
    else if {game.state} is "meeting":
        muteDead()

on voice channel join:
    updateCall()

        