function kickPlayer(p: player):

    
    # TELEPORTA TODOS OS JOGADORES
    

    loop all players:

        teleport loop-player to location(127, -59, 219, world("amongmc"))
        set yaw of loop-player to -90
        set pitch of loop-player to 0
    
    teleport {_p} to location(132, -59, 219, world("amongmc"))
    set yaw of {_p} to 90
    set pitch of {_p} to 0

    showEjectMessage({_p})

    if {config.confirmEjects} is true:
        wait 5 seconds
    else:
        wait 3 seconds

    
    execute console command "fill 134 -57 218 134 -59 220 air"

    wait 5 ticks
    
    set velocity of {_p} to vector(8, 0, 0)

    wait 10 ticks

    execute console command "fill 134 -57 218 134 -59 220 iron_block"
    
    kill({_p})

    wait 10 ticks
    if {game.state} is "meeting":
        set {game.state} to "running"
        teleportMeeting()
        updateCall()

function typewriterSubtitle(text: text, color: text, delay: timespan = 2 ticks):

    set {_current} to ""

    loop length of {_text} times:

        set {_current} to "%{_current}%%character at loop-number of {_text}%"

        execute console command "title @a times 0 20 5"
        execute console command "title @a title {""text"":""%{_current}%"", ""color"":""%{_color}%""}"

        wait {_delay}

function showEjectMessage(p: player):

    # Primeira mensagem
    if {game.impostors::*} contains {_p}:
        if {config.confirmEjects} is true:
            typewriterSubtitle("%{_p}% era um impostor.","red")
        else:
            typewriterSubtitle("%{_p}% foi ejetado.","gray")
    else:
        if {config.confirmEjects} is true:
            typewriterSubtitle("%{_p}% não era um impostor.", "aqua")
        else:
            typewriterSubtitle("%{_p}% foi ejetado.", "gray")

    if {config.confirmEjects} is true:
        wait 3 seconds

        # Segunda mensagem
        set {_remaining} to 0
        if {game.impostors::*} contains {_p}:
            add -1 to {_remaining}
            
        loop {game.impostors::*}:
            if {game.ghosts::*} does not contain loop-value:
                add 1 to {_remaining}

        if {_remaining} = 1:
            typewriterSubtitle("1 impostor restante.", "red")
        else:
            typewriterSubtitle("%{_remaining}% impostores restantes.", "red")