function kill(p: player):

    if {game.ghosts::*} contains {_p}:
        stop

    add {_p} to {game.ghosts::*}

    loop all players:
        hide {_p} from loop-player

    checkEndGame()
    updateVitals()


function revive(p: player):

    if {game.ghosts::*} does not contain {_p}:
        stop

    remove {_p} from {game.ghosts::*}

    loop all players:
        reveal {_p} to loop-player

on attack attempt:
    if attacker's gamemode is creative:
        stop
    cancel event
    if {game.state} is not "running":
        stop
    if {game.impostors::*} does not contain attacker:
        stop
    if {killCooldown.%uuid of attacker%} > 0:
        stop
    if {vent.active.%uuid of attacker%} is true:
        stop

    if {game.impostors::*} contain victim:
        stop

    if type of victim is not player:
        stop

    if {game.ghosts::*} contain attacker:
        stop

    if {game.ghosts::*} contain victim:
        stop

    if distance between attacker and victim > {config.killRange}:
        stop

    spawnBody(victim)
    kill(victim)
    play sound "minecraft:item.trident.hit" with volume 1 and pitch 0.6 to attacker
    play sound "minecraft:item.trident.hit" with volume 1 and pitch 0.6 to victim
    close victim's inventory



    set {_current} to ""
    set {_text} to "Você foi morto!"
    set {_color} to "red"

    loop length of {_text} times:

        set {_current} to "%{_current}%%character at loop-number of {_text}%"

        execute console command "title %victim% times 0 20 5"
        execute console command "title %victim% title {""text"":""%{_current}%"", ""color"":""%{_color}%""}"



    set {killCooldown.%uuid of attacker%} to {config.killCooldown}

every 1 second:

    loop {game.impostors::*}:

        if {vent.active.%uuid of loop-value%} is true:
            continue

        if {killCooldown.%uuid of loop-value%} > 0:
            remove 1 from {killCooldown.%uuid of loop-value%}
            updateScoreboard(loop-value)

on right click on armor stand:
    if clicked entity does not have scoreboard tag "among_body":
        stop
    if {game.ghosts::*} contains player:
        stop
    if {game.state} is not "running":
        stop
    set {game.state} to "meeting"
    cancel event

    set {_dead} to {bodyOwner.%uuid of clicked entity%} parsed as player

    broadcast "&cO corpo de %chatColor({_dead})%%name of {_dead}% &cfoi encontrado!"

    startMeeting(player)

function spawnBody(p: player):

    set {_loc} to location of {_p}
    subtract 1 from y-coordinate of {_loc}

    spawn armor stand at {_loc}

    set {_body} to last spawned entity
    add "among_body" to scoreboard tags of {_body}

    set {body.%uuid of {_p}%} to {_body}
    set {bodyOwner.%uuid of {_body}%} to uuid of {_p}

    set {_nbt} to nbt compound from "{NoGravity:1b,Invisible:1b,ShowArms:1b,NoBasePlate:1b,Pose:{Body:[90f,0f,0f],Head:[85f,0f,0f],LeftLeg:[90f,0f,0f],RightLeg:[90f,0f,0f],LeftArm:[90f,0f,0f],RightArm:[90f,0f,0f]}}"
    add {_nbt} to nbt of {_body}

    set helmet of {_body} to skull of {_p}

    set chestplate of {_body} to chestplate of {_p}
    set leggings of {_body} to leggings of {_p}
    set boots of {_body} to boots of {_p}

    set tool of {_body} to tool of {_p}

function startKillCooldown(seconds: number):
    loop {game.impostors::*}:
        set {killCooldown.%uuid of loop-value%} to {_seconds}

        