function clean_lens(p: player, step: number):

    set {_inv} to chest inventory with 5 rows named "&8Limpar Lente"

    set {lens.step.%uuid of {_p}%} to {_step}

    loop 45 times:
        set slot (loop-number - 1) of {_inv} to black stained glass pane named " "


    set {_lens::*} to 2,3,4,10,11,12,13,14,19,20,21,22,23,28,29,30,31,32,38,39,40


    loop {_lens::*}:
        set slot loop-value of {_inv} to light gray stained glass pane named "&7Lente"

    set {_dirty::*} to {_lens::*}
    set {_amount} to random integer between 10 and 14

    loop {_amount} times:

        set {_slot} to random element out of {_dirty::*}
        remove {_slot} from {_dirty::*}

        set {_color} to random integer between 1 and 3

        if {_color} = 1:
            set slot {_slot} of {_inv} to brown stained glass pane named "&6Sujeira"

        else if {_color} = 2:
            set slot {_slot} of {_inv} to orange stained glass pane named "&6Sujeira"

        else:
            set slot {_slot} of {_inv} to yellow stained glass pane named "&6Sujeira"

    set slot 25 of {_inv} to wet sponge named "&eEsponja"

    set slot 43 of {_inv} to spyglass named "&7Lente do telescópio"

    set {lens.running.%uuid of {_p}%} to true
    set {lens.step.%uuid of {_p}%} to {_step}

    open {_inv} to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Limpar Lente":
        stop

    if click type is left mouse button with shift or right mouse button with shift or double click using mouse:
        cancel event
        stop


    set {_lens::*} to 2,3,4,10,11,12,13,14,19,20,21,22,23,28,29,30,31,32,38,39,40

    if clicked slot is 25:
        if player is from floodgate:
            wait 1 tick
            if player's cursor slot is wet sponge:
                set player's cursor slot to air
                set slot 25 of event-inventory to wet sponge
        stop


    if clicked slot is 43:
        cancel event
        stop


    if player's cursor slot is not wet sponge:
        cancel event
        stop

    if name of event-item is not "&6Sujeira":
        cancel event
        stop

    cancel event

    set slot (index of clicked slot) of event-inventory to light gray stained glass pane named "&7Lente"

    play sound "minecraft:block.sponge.absorb" with volume 0.6 and pitch 1.3 to player

    loop {_lens::*}:

        set {_item} to slot loop-value of event-inventory

        if {_item} is brown stained glass pane:
            stop

        if {_item} is orange stained glass pane:
            stop

        if {_item} is yellow stained glass pane:
            stop

    close player's inventory
    advanceTaskStep(player, "clean_lens", {wires.step.%uuid of player%})


on inventory close:

    if name of event-inventory is "&8Limpar Lente":
        if player's cursor slot is not air:
            set player's cursor slot to air