function open_valve(p: player, step: number):

    set {_frame} to {_p}'s targeted entity
    set {_nbt} to nbt of {_frame}

    set {_currentRotation} to byte tag "ItemRotation" of {_nbt}
    set {_newRotation} to mod({_currentRotation} + 1, 8)

    set byte tag "ItemRotation" of nbt of {_frame} to {_newRotation}

    play sound "minecraft:block.chain.place" with volume 0.8 and pitch 0.9 to {_p}

    if {_newRotation} is 0:

        play sound "minecraft:block.iron_door.open" with volume 0.8 and pitch 1.2 to {_p}
        play sound "minecraft:block.note_block.chime" with volume 0.6 and pitch 1.6 to {_p}

        add 1 to {valve.session}
        advanceTaskStep({_p}, "open_valve")
        stop
        
    add 1 to {valve.session}
    set {_session} to {valve.session}

    wait 3 seconds

    if {valve.session} is {_session}:
        set byte tag "ItemRotation" of nbt of {_frame} to 0

        play sound "minecraft:block.chain.break" with volume 0.6 and pitch 0.8 to {_p}