function organize_books(p: player, step: number):

    set {_pool::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9

    set {_inv} to chest inventory with 1 row named "&6Organizar Livros"

    loop 9 times:

        set {_n} to random element out of {_pool::*}
        remove {_n} from {_pool::*}

        if {_n} = 1:
            set {_roman} to "I"
        else if {_n} = 2:
            set {_roman} to "II"
        else if {_n} = 3:
            set {_roman} to "III"
        else if {_n} = 4:
            set {_roman} to "IV"
        else if {_n} = 5:
            set {_roman} to "V"
        else if {_n} = 6:
            set {_roman} to "VI"
        else if {_n} = 7:
            set {_roman} to "VII"
        else if {_n} = 8:
            set {_roman} to "VIII"
        else:
            set {_roman} to "IX"

        set {_book} to book named "&eComo sobreviver a um impostor %{_roman}%"
        set int tag "AmongMCBook" of custom nbt of {_book} to {_n}

        set slot (loop-number - 1) of {_inv} to {_book}

    open {_inv} to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&6Organizar Livros":
        stop
    if click type is left mouse button with shift or right mouse button with shift:
        cancel event
        stop

    wait 1 tick

    if player is from floodgate:
        set {_item} to player's cursor slot
        if {_item} is not air:
            loop 9 times:
                if slot (loop-number - 1) of event-inventory is air:
                    set slot (loop-number - 1) of event-inventory to {_item}
                    set player's cursor slot to air

                    stop loop

    loop 9 times:

        set {_item} to slot (loop-number - 1) of event-inventory

        if {_item} is air:
            stop

        if int tag "AmongMCBook" of custom nbt of {_item} is not loop-number:
            stop

    close player's inventory
    advanceTaskStep(player, "organize_books")

on inventory close:

    if name of event-inventory is "&6Organizar Livros":

        if player's cursor slot is not air:
            set player's cursor slot to air