function prepare_reagent(p: player, step: number):

    if {reagent.processing.%uuid of {_p}%} is true:
        send "&cO reagente ainda está descansando. Você quer mesmo mexer nele? Da última vez quase ganharam uma terceira sobrancelha." to {_p}
        stop

    set {_inv} to chest inventory with 4 rows named "&8Preparar Reagente"

    delete {reagent.recipe.%uuid of {_p}%::*}
    delete {reagent.progress.%uuid of {_p}%}
    delete {reagent.length.%uuid of {_p}%}

    loop 36 times:
        set slot (loop-number - 1) of {_inv} to gray stained glass pane named " "

    set slot 13 of {_inv} to cauldron named "&bBéquer"

    loop 28,29,30,32,33,34:
        set slot loop-value of {_inv} to air

    delete {_pool::*}

    add health potion named "&cReagente Vermelho" with item flag hide additional tooltip to {_pool::*}
    add potion named "&9Reagente Azul" with item flag hide additional tooltip to {_pool::*}
    add night vision potion named "&aReagente Verde" with item flag hide additional tooltip to {_pool::*}
    add strength potion named "&eReagente Amarelo" with item flag hide additional tooltip to {_pool::*}
    add regeneration potion named "&5Reagente Rosa" with item flag hide additional tooltip to {_pool::*}
    add invisibility potion named "&fCatalisador" with item flag hide additional tooltip to {_pool::*}

    set {_slots::*} to 28,29,30,32,33,34

    loop 6 times:

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set {_item} to random element out of {_pool::*}
        remove {_item} from {_pool::*}

        set slot {_slot} of {_inv} to {_item}

    set {_len} to random integer between 3 and 4
    set {reagent.length.%uuid of {_p}%} to {_len}

    delete {_types::*}

    add "&cReagente Vermelho" to {_types::*}
    add "&9Reagente Azul" to {_types::*}
    add "&aReagente Verde" to {_types::*}
    add "&eReagente Amarelo" to {_types::*}
    add "&5Reagente Rosa" to {_types::*}
    add "&fCatalisador" to {_types::*}

    loop {_len} times:

        set {_name} to random element out of {_types::*}

        set {reagent.recipe.%uuid of {_p}%::%loop-number%} to {_name}

        if {_name} is "&cReagente Vermelho":
            set {_potion} to health potion named "&cReagente Vermelho" 

        else if {_name} is "&9Reagente Azul":
            set {_potion} to potion named "&9Reagente Azul" 

        else if {_name} is "&aReagente Verde":
            set {_potion} to night vision potion named "&aReagente Verde"

        else if {_name} is "&eReagente Amarelo":
            set {_potion} to strength potion named "&eReagente Amarelo" 

        else if {_name} is "&5Reagente Rosa":
            set {_potion} to regeneration potion named "&5Reagente Rosa"

        else:
            set {_potion} to invisibility potion named "&fCatalisador"

        add hide additional tooltip to item flags of {_potion}

        set slot (4 + loop-number) of {_inv} to {_potion}

    if {_len} < 4:

        set slot 8 of {_inv} to black stained glass pane named " "

    set {reagent.progress.%uuid of {_p}%} to 0


    if {reagent.ready.%uuid of {_p}%} is true:
        set slot 13 of {_inv} to potion named "&aReagente Pronto" with item flags hide additional tooltip
        
        loop 7 times:
            set slot (loop-number + 27) of {_inv} to gray stained glass pane named " "

    open {_inv} to {_p}

    play sound "minecraft:block.brewing_stand.brew" with volume 0.5 and pitch 1.2 to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Preparar Reagente":
        stop

    if click type is left mouse button with shift or right mouse button with shift or double click using mouse:
        cancel event
        stop

    if clicked slot is 5 or 6 or 7 or 8:
        cancel event
        stop


    if clicked slot is 28 or 29 or 30 or 32 or 33 or 34:
        if player is from floodgate:
            stop
        cancel event
        if {reagent.ready.%uuid of player%} is not true:
            set player's cursor slot to event-item
            stop

    if clicked slot is not 28 or 29 or 30 or 32 or 33 or 34 or 13:
        cancel event
        stop

    if clicked slot is 13:
        if {reagent.ready.%uuid of player%} is not true:

            if player's cursor slot is air:
                cancel event
                stop


            set {_item} to player's cursor slot
            set {_name} to name of {_item}

            set {_next} to {reagent.progress.%uuid of player%} + 1
            set {_expected} to {reagent.recipe.%uuid of player%::%{_next}%}

            if {_name} is {_expected}:

                cancel event

                set player's cursor slot to air

                add 1 to {reagent.progress.%uuid of player%}

                play sound "minecraft:block.brewing_stand.brew" with volume 0.8 and pitch 1.2 to player

                if {reagent.progress.%uuid of player%} >= {reagent.length.%uuid of player%}:

                    play sound "minecraft:entity.player.levelup" with volume 1 and pitch 1.2 to player
                    set slot 13 of event-inventory to brewing stand named "&bMisturando..."

                    wait 1 second

                    close player's inventory

                    set {reagent.processing.%uuid of player%} to true
                    delete {reagent.progress.%uuid of player%}

                    send "&eReagente misturado com sucesso! Agora deixe ele descansar por 1 minuto. Vou te avisar no chat quando estiver pronto." to player
                    send "&7Não mexa no caldeirão. Cientistas anteriores fizeram isso e descobriram novos tons de explosão." to player
                    set {_session} to {game.session}
                    wait 60 seconds

                    if {_session} is not {game.session}:
                        stop

                    set {reagent.ready.%uuid of player%} to true
                    delete {reagent.processing.%uuid of player%}

                    send "&aSeu reagente finalmente está pronto! Pode voltar ao laboratório para buscar." to player

                    play sound "minecraft:entity.player.levelup" with volume 1 and pitch 1.2 to player

                if player is from floodgate:
                    set player's cursor slot to {_item} 

                stop

            else:

                cancel event

                set player's cursor slot to air

                play sound "minecraft:entity.generic.explode" with volume 0.8 and pitch 1 to player

                close player's inventory

                send "&cExcelente. Você acabou de inventar um reagente completamente inútil. A boa notícia é que o laboratório continua inteiro. Por enquanto." to player

                delete {reagent.recipe.%uuid of player%::*}
                delete {reagent.progress.%uuid of player%}
                delete {reagent.length.%uuid of player%}

                stop

    if clicked slot is 13:
        if name of event-item is "&aReagente Pronto":

            cancel event

            close player's inventory

            advanceTaskStep(player, "prepare_reagent")

            stop

    if clicked slot is 13:
        cancel event
        stop



on inventory close:

    if name of event-inventory is "&8Preparar Reagente":

        if player's cursor slot is not air:
            set player's cursor slot to air