function sequence_fission(p: player, step: number):

    set {_inv} to chest inventory with 2 rows named "&8Sequenciar Fissão"

    set {fission.next.%uuid of {_p}%} to 1

    loop 18 times:
        set slot (loop-number - 1) of {_inv} to gray stained glass pane named " "

    set {_slots::*} to 2,3,4,5,6,11,12,13,14,15

    set {_nums::*} to 1,2,3,4,5,6,7,8,9,10

    loop 10 times:

        set {_slot} to random element out of {_slots::*}
        remove {_slot} from {_slots::*}

        set {_num} to random element out of {_nums::*}
        remove {_num} from {_nums::*}

        set {_item} to light gray stained glass pane named "&f%{_num}%"
        set amount of {_item} to {_num}

        set slot {_slot} of {_inv} to {_item}

    open {_inv} to {_p}

    play sound "minecraft:block.beacon.activate" with volume 0.5 and pitch 1.6 to {_p}


on inventory click:

    if holder of event-inventory is set:
        stop

    if name of event-inventory is not "&8Sequenciar Fissão":
        stop

    cancel event

    if clicked slot is not 2 or 3 or 4 or 5 or 6 or 11 or 12 or 13 or 14 or 15:
        stop

    set {_expected} to {fission.next.%uuid of player%}
    set {_value} to amount of clicked slot

    if {_value} = {_expected}:

        set slot (index of clicked slot) of event-inventory to lime stained glass pane named "&a%{_value}%"
        set item amount of slot (index of clicked slot) of event-inventory to {_value}

        play sound "minecraft:block.note_block.pling" with volume 0.6 and pitch (0.7 + ({_value} * 0.08)) to player

        add 1 to {fission.next.%uuid of player%}

        if {fission.next.%uuid of player%} = 11:

            wait 5 ticks

            close player's inventory
            advanceTaskStep(player, "sequence_fission")

        stop

    loop 2,3,4,5,6,11,12,13,14,15:

        set slot loop-value of event-inventory to red stained glass pane named "&cERRO"

    play sound "minecraft:block.note_block.bass" with volume 1 and pitch 0.6 to player
    play sound "minecraft:block.beacon.deactivate" with volume 0.8 and pitch 0.8 to player

    wait 1 second

    close player's inventory

    send "&cImpressionante. Você não soube contar e agora os átomos estão fora de lugar."